In [1]:
#Dependencies
import pandas as pd
import numpy as np
from sportsreference.nba.schedule import Schedule
from datetime import date

In [2]:
#bucks schedule object
bucks_schedule_20 = Schedule('MIL', 2020)

In [3]:
#bucks data frame *focusing on pre-bubble regular season game"
dates = []
results = []
locations = []
game_nums = []
opponents = []

for game in bucks_schedule_20:
    
    if game.playoffs == False and game.game < 66:
        print(game.datetime)  
        print(game.result) 
        print(game.location)
        print(game.game)
        dates.append(game.datetime)
        results.append(game.result)
        locations.append(game.location)
        game_nums.append(game.game)
        opponents.append(game.opponent_abbr)

2019-10-24 00:00:00
Win
Away
1
2019-10-26 00:00:00
Loss
Home
2
2019-10-28 00:00:00
Win
Home
3
2019-10-30 00:00:00
Loss
Away
4
2019-11-01 00:00:00
Win
Away
5
2019-11-02 00:00:00
Win
Home
6
2019-11-04 00:00:00
Win
Away
7
2019-11-06 00:00:00
Win
Away
8
2019-11-08 00:00:00
Loss
Away
9
2019-11-10 00:00:00
Win
Away
10
2019-11-14 00:00:00
Win
Home
11
2019-11-16 00:00:00
Win
Away
12
2019-11-18 00:00:00
Win
Away
13
2019-11-20 00:00:00
Win
Away
14
2019-11-21 00:00:00
Win
Home
15
2019-11-23 00:00:00
Win
Home
16
2019-11-25 00:00:00
Win
Home
17
2019-11-27 00:00:00
Win
Home
18
2019-11-29 00:00:00
Win
Away
19
2019-11-30 00:00:00
Win
Home
20
2019-12-02 00:00:00
Win
Home
21
2019-12-04 00:00:00
Win
Away
22
2019-12-06 00:00:00
Win
Home
23
2019-12-09 00:00:00
Win
Home
24
2019-12-11 00:00:00
Win
Home
25
2019-12-13 00:00:00
Win
Away
26
2019-12-14 00:00:00
Win
Home
27
2019-12-16 00:00:00
Loss
Home
28
2019-12-19 00:00:00
Win
Home
29
2019-12-21 00:00:00
Win
Away
30
2019-12-22 00:00:00
Win
Home
31
2019-12-25 00:00:00
Loss
Away
32
2019-12-27 00:00:00
Win
Away
33
2019-12-28 00:00:00
Win
Home
34
2019-12-30 00:00:00
Win
Away
35
2020-01-01 00:00:00
Win
Home
36
2020-01-04 00:00:00
Win
Home
37
2020-01-06 00:00:00
Loss
Away
38
2020-01-08 00:00:00
Win
Away
39
2020-01-10 00:00:00
Win
Away
40
2020-01-11 00:00:00
Win
Away
41
2020-01-14 00:00:00
Win
Home
42
2020-01-16 00:00:00
Win
Home
43
2020-01-18 00:00:00
Win
Away
44
2020-01-20 00:00:00
Win
Home
45
2020-01-24 00:00:00
Win
Away
46
2020-01-28 00:00:00
Win
Home
47
2020-01-31 00:00:00
Loss
Home
48
2020-02-02 00:00:00
Win
Home
49
2020-02-04 00:00:00
Win
Away
50
2020-02-06 00:00:00
Win
Home
51
2020-02-08 00:00:00
Win
Away
52
2020-02-10 00:00:00
Win
Home
53
2020-02-12 00:00:00
Loss
Away
54
2020-02-20 00:00:00
Win
Away
55
2020-02-22 00:00:00
Win
Home
56
2020-02-24 00:00:00
Win
Away
57
2020-02-25 00:00:00
Win
Away
58
2020-02-28 00:00:00
Win
Home
59
2020-03-01 00:00:00
Win
Away
60
2020-03-02 00:00:00
Loss
Away
61
2020-03-04 00:00:00
Win
Home
62
2020-03-06 00:00:00
Loss
Away
63
2020-03-08 00:00:00
Loss
Away
64
2020-03-09 00:00:00
Loss
Away
65

In [4]:
#creating bucks dictionary
bucks_dict = {
    "dates": dates,
    "results": results,
    "locations": locations,
    "game_nums": game_nums,
    "opponent": opponents
}

#creating bucks data frame
bucks_df = pd.DataFrame(bucks_dict)
bucks_df

        dates results locations  game_nums opponent
0  2019-10-24     Win      Away          1      HOU
1  2019-10-26    Loss      Home          2      MIA
2  2019-10-28     Win      Home          3      CLE
3  2019-10-30    Loss      Away          4      BOS
4  2019-11-01     Win      Away          5      ORL
..        ...     ...       ...        ...      ...
60 2020-03-02    Loss      Away         61      MIA
61 2020-03-04     Win      Home         62      IND
62 2020-03-06    Loss      Away         63      LAL
63 2020-03-08    Loss      Away         64      PHO
64 2020-03-09    Loss      Away         65      DEN

[65 rows x 5 columns]

In [5]:
#finding the number of games between each game
bucks_df["date_diff"] = 0

for i in range(1,len(bucks_df)):    
    bucks_df["date_diff"][i] = bucks_df["dates"][i] - bucks_df["dates"][(i-1)]
    
bucks_df

C:\Users\Administrator\anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

        dates results locations  game_nums opponent        date_diff
0  2019-10-24     Win      Away          1      HOU                0
1  2019-10-26    Loss      Home          2      MIA  2 days 00:00:00
2  2019-10-28     Win      Home          3      CLE  2 days 00:00:00
3  2019-10-30    Loss      Away          4      BOS  2 days 00:00:00
4  2019-11-01     Win      Away          5      ORL  2 days 00:00:00
..        ...     ...       ...        ...      ...              ...
60 2020-03-02    Loss      Away         61      MIA  1 days 00:00:00
61 2020-03-04     Win      Home         62      IND  2 days 00:00:00
62 2020-03-06    Loss      Away         63      LAL  2 days 00:00:00
63 2020-03-08    Loss      Away         64      PHO  2 days 00:00:00
64 2020-03-09    Loss      Away         65      DEN  1 days 00:00:00

[65 rows x 6 columns]

In [6]:
#inserting value for the date diff in the first game
#using the difference between the last preseason game and the first regular season game
bucks_df["date_diff"][0] = 5

#converting to a time delta
bucks_df["date_diff"][0] = pd.to_timedelta(bucks_df["date_diff"][0], unit = "D")


bucks_df

C:\Users\Administrator\anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\Administrator\anaconda3\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

        dates results locations  game_nums opponent        date_diff
0  2019-10-24     Win      Away          1      HOU  5 days 00:00:00
1  2019-10-26    Loss      Home          2      MIA  2 days 00:00:00
2  2019-10-28     Win      Home          3      CLE  2 days 00:00:00
3  2019-10-30    Loss      Away          4      BOS  2 days 00:00:00
4  2019-11-01     Win      Away          5      ORL  2 days 00:00:00
..        ...     ...       ...        ...      ...              ...
60 2020-03-02    Loss      Away         61      MIA  1 days 00:00:00
61 2020-03-04     Win      Home         62      IND  2 days 00:00:00
62 2020-03-06    Loss      Away         63      LAL  2 days 00:00:00
63 2020-03-08    Loss      Away         64      PHO  2 days 00:00:00
64 2020-03-09    Loss      Away         65      DEN  1 days 00:00:00

[65 rows x 6 columns]

In [7]:
#Converting the date difference series back into an integer for easier comparisons
for day in range(0,len(bucks_df["date_diff"])):
    bucks_df["date_diff"][day] = bucks_df["date_diff"][day] / np.timedelta64(1, 'D')


bucks_df

C:\Users\Administrator\anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

        dates results locations  game_nums opponent date_diff
0  2019-10-24     Win      Away          1      HOU         5
1  2019-10-26    Loss      Home          2      MIA         2
2  2019-10-28     Win      Home          3      CLE         2
3  2019-10-30    Loss      Away          4      BOS         2
4  2019-11-01     Win      Away          5      ORL         2
..        ...     ...       ...        ...      ...       ...
60 2020-03-02    Loss      Away         61      MIA         1
61 2020-03-04     Win      Home         62      IND         2
62 2020-03-06    Loss      Away         63      LAL         2
63 2020-03-08    Loss      Away         64      PHO         2
64 2020-03-09    Loss      Away         65      DEN         1

[65 rows x 6 columns]

In [8]:
#date diff is only the difference between the two games
#creating a column to represent the "rest" days between the games
#"rest" in this case is the days between each game where a game is not being played and does not account for practices
bucks_df["rest"] = bucks_df["date_diff"] - 1 

bucks_df.head()

       dates results locations  game_nums opponent date_diff rest
0 2019-10-24     Win      Away          1      HOU         5    4
1 2019-10-26    Loss      Home          2      MIA         2    1
2 2019-10-28     Win      Home          3      CLE         2    1
3 2019-10-30    Loss      Away          4      BOS         2    1
4 2019-11-01     Win      Away          5      ORL         2    1

In [9]:
#write to csv
bucks_df.to_csv("../data/bucks_19_20_rest.csv", index = False)