In [75]:
#depenencies

import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.feature_selection import RFE, SelectKBest, chi2
from sklearn import svm
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegressionCV

In [28]:
#import data
training_data = pd.read_csv('data/training_data.csv')

training_data

,dates,results,locations,game_nums,opponent,date_diff,rest,opp_date_diff,opp_rest,rest_diff,abbrv
0,2017-10-18,Win,Away,1,BOS,10,9,10.0,9.0,0.0,MIL
1,2017-10-20,Loss,Home,2,CLE,2,1,3.0,2.0,-1.0,MIL
2,2017-10-21,Win,Home,3,POR,1,0,1.0,0.0,0.0,MIL
3,2017-10-23,Win,Home,4,CHO,2,1,2.0,1.0,0.0,MIL
4,2017-10-26,Loss,Home,5,BOS,3,2,2.0,1.0,1.0,MIL
...,...,...,...,...,...,...,...,...,...,...,...
4915,2017-04-05,Win,Away,78,BOS,1,0,3.0,2.0,-2.0,CLE
4916,2017-04-07,Loss,Home,79,ATL,2,1,1.0,0.0,1.0,CLE
4917,2017-04-09,Loss,Away,80,ATL,2,1,2.0,1.0,0.0,CLE
4918,2017-04-10,Loss,Away,81,MIA,1,0,2.0,1.0,-1.0,CLE
4919,2017-04-12,Loss,Home,82,TOR,2,1,3.0,2.0,-1.0,CLE

In [29]:
#feature engineering

# creating instance of labelencoder
labelencoder = LabelEncoder()
# Assigning numerical values and storing in another column

training_data['opponent_lab'] = labelencoder.fit_transform(training_data['opponent'])
training_data['locations_lab'] = labelencoder.fit_transform(training_data['locations'])
training_data['abbrv_lab'] = labelencoder.fit_transform(training_data['abbrv'])
training_data['results_lab'] = labelencoder.fit_transform(training_data['results'])

training_data

,dates,results,locations,game_nums,opponent,date_diff,rest,opp_date_diff,opp_rest,rest_diff,abbrv,opponent_lab,locations_lab,abbrv_lab,results_lab
0,2017-10-18,Win,Away,1,BOS,10,9,10.0,9.0,0.0,MIL,1,0,16,1
1,2017-10-20,Loss,Home,2,CLE,2,1,3.0,2.0,-1.0,MIL,5,1,16,0
2,2017-10-21,Win,Home,3,POR,1,0,1.0,0.0,0.0,MIL,24,1,16,1
3,2017-10-23,Win,Home,4,CHO,2,1,2.0,1.0,0.0,MIL,4,1,16,1
4,2017-10-26,Loss,Home,5,BOS,3,2,2.0,1.0,1.0,MIL,1,1,16,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4915,2017-04-05,Win,Away,78,BOS,1,0,3.0,2.0,-2.0,CLE,1,0,5,1
4916,2017-04-07,Loss,Home,79,ATL,2,1,1.0,0.0,1.0,CLE,0,1,5,0
4917,2017-04-09,Loss,Away,80,ATL,2,1,2.0,1.0,0.0,CLE,0,0,5,0
4918,2017-04-10,Loss,Away,81,MIA,1,0,2.0,1.0,-1.0,CLE,15,0,5,0
4919,2017-04-12,Loss,Home,82,TOR,2,1,3.0,2.0,-1.0,CLE,27,1,5,0

In [30]:
training_data.columns

Index(['dates', 'results', 'locations', 'game_nums', 'opponent', 'date_diff',
       'rest', 'opp_date_diff', 'opp_rest', 'rest_diff', 'abbrv',
       'opponent_lab', 'locations_lab', 'abbrv_lab', 'results_lab'],
      dtype='object')

In [32]:
#separate x and y
data = training_data[['game_nums', 'date_diff',
       'rest', 'opp_date_diff', 'opp_rest', 'rest_diff',
       'opponent_lab', 'locations_lab', 'abbrv_lab', 'results_lab']]

X = data.iloc[:,0:8]
y = data.iloc[:,9].to_list()

In [36]:
#svm estimator and recursive feature selection

svm_estimator = svm.SVC(kernel='linear') 


rfe = RFE(estimator= svm_estimator, 
          verbose=1, 
          n_features_to_select= 4
         )

rfe.fit(X, y)

Fitting estimator with 8 features.
Fitting estimator with 7 features.
Fitting estimator with 6 features.
Fitting estimator with 5 features.

RFE(estimator=SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None,
                  coef0=0.0, decision_function_shape='ovr', degree=3,
                  gamma='scale', kernel='linear', max_iter=-1,
                  probability=False, random_state=None, shrinking=True,
                  tol=0.001, verbose=False),
    n_features_to_select=4, step=1, verbose=1)

In [37]:
#top 4 features
cols = rfe.get_support(indices=True)
X_new = X.iloc[:,cols]
X_new.columns

Index(['date_diff', 'opp_rest', 'rest_diff', 'locations_lab'], dtype='object')

In [40]:
#Standardize the input features
scaler = MinMaxScaler(feature_range=(.1,.9) #TODO: provide the min and max values for the features
                     )

X_stand = scaler.fit_transform(X)

In [42]:
#standardized rfe

svm_estimator = svm.SVC(kernel='linear') #initialize the SVM estimator

#TODO: Recursive Feature Elimination
rfe = RFE(estimator= svm_estimator, #TODO: provide the SVM estimator 
          verbose=1, 
          n_features_to_select= 4#TODO: enter the number of required features
         )

rfe.fit(X_stand, y) #Note: this may take a few minutes to complete

Fitting estimator with 8 features.
Fitting estimator with 7 features.
Fitting estimator with 6 features.
Fitting estimator with 5 features.

RFE(estimator=SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None,
                  coef0=0.0, decision_function_shape='ovr', degree=3,
                  gamma='scale', kernel='linear', max_iter=-1,
                  probability=False, random_state=None, shrinking=True,
                  tol=0.001, verbose=False),
    n_features_to_select=4, step=1, verbose=1)

In [43]:
#TODO: display the names of the selected features below
cols = rfe.get_support(indices=True)
X_new = X.iloc[:,cols]
X_new.columns

Index(['game_nums', 'rest', 'rest_diff', 'locations_lab'], dtype='object')

In [47]:

X_train, X_test, y_train, y_test = train_test_split(
X, y, test_size=0.3, random_state=42)
scaler = preprocessing.StandardScaler().fit(X_train)
X_train_transformed = scaler.transform(X_train)
clf = svm.SVC(C=1).fit(X_train_transformed, y_train)
X_test_transformed = scaler.transform(X_test)
clf.score(X_test_transformed, y_test)

0.5928184281842819

In [48]:
from sklearn.model_selection import cross_val_score
clf = svm.SVC(kernel='linear', C=1, random_state=42)
scores = cross_val_score(clf, X, y, cv=5)
scores

array([0.55691057, 0.59146341, 0.59044715, 0.58028455, 0.58739837])

In [110]:
#random forest ensemble
#separate x and y
data = training_data[['game_nums', 'date_diff',
       'rest', 'opp_date_diff', 'opp_rest', 'rest_diff',
       'opponent_lab', 'locations_lab', 'abbrv_lab', 'results_lab']]

X = data.iloc[:,0:8].to_numpy()
y = data.iloc[:,9].to_list()

In [111]:
#splitting into training and test sets
seed = 42

#Standardize the input features
scaler = MinMaxScaler(feature_range=(.1,.9) #TODO: provide the min and max values for the features
                     )

X = scaler.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(X,y,
                                                    test_size = .35, 
                                                    random_state = seed,
                                                    stratify = y
                                                   )

In [112]:
#Create the RandomForestClassifier

rf_classifier = RandomForestClassifier(criterion= 'gini', 
                                    max_depth= 15,     
                                    max_features= "auto",  
                                    min_samples_split= 10, 
                                    n_estimators= 100, 
                                    random_state= 100 
                                    )

#TODO: Train classifer using the `fit` method
rf_classifier.fit(X_train,y_train)

#TODO: Make predictions with the test set
y_pred = rf_classifier.predict(X_test)

#TODO: evaluate the accuracy
round(accuracy_score(y_test,y_pred),4)

0.5871

In [113]:
#log res

clf = LogisticRegressionCV(cv=5, random_state=100).fit(X_train, y_train)
y_pred = clf.predict(X_test)

# clf.score(X, y)
round(accuracy_score(y_test,y_pred),4)

0.5772

0.5772